In [3]:
#numpy
import numpy as np
a=np.array([1,2,3])
a
print(a)
type(a)


[1 2 3]


numpy.ndarray

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)



[[1 2 3]
 [4 5 6]]


In [10]:
a=np.array([[1,2,3],[4,5,7]])
print(a)


[[1 2 3]
 [4 5 7]]


In [24]:
import numpy as np #specification
a=np.array([1,2],ndmin=4)
print(a)
a.ndim


[[[[1 2]]]]


4

In [33]:
a=np.array([[1,3,2],[4,5,6]]) #accesing
print(a[1,2])
print(a[1,1])
a[1,2]

6
5


6

In [5]:
import numpy as np
b=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(b)
print(b.ndim)
print(b[0,1,2])
b[1,-1]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]
3
6


array([11, 12, 13])

In [49]:
#arange
a=np.arange(10)
print(a)
a=np.arange(0,10,2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [69]:
#ones

c=np.ones(2, dtype=int)
c

array([1, 1])

In [63]:
d=np.zeros(4)
d

array([0., 0., 0., 0.])

In [71]:
a=np.empty(4)
a

array([8.89324794e-312, 8.89324794e-312, 8.89324794e-312, 1.26974871e-321])

In [74]:
a=np.array([1,2,3,4])
print(a.min())
print(a.max())
a.sum()


1
4


10

In [78]:
print(a.dtype)
a.dtype.name



int32


'int32'

In [83]:
a=np.array([1,2,3,4,5])
x=a.copy()
y=a.view()
a[0]=0
print(a)
print(x)
print(y)
print(x.base)#base
print(y.base)

[0 2 3 4 5]
[1 2 3 4 5]
[0 2 3 4 5]
None
[0 2 3 4 5]


In [14]:
#shape 

a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
b=np.array([[1,3,2],[4,5,7]])
print(b.shape)
c=np.array([1,2,3,4,5],ndmin=5)
print(c.shape)
print(c)


(2, 3)
(2, 3)
(1, 1, 1, 1, 5)
[[[[[1 2 3 4 5]]]]]


In [16]:
#reshape
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
#1d to3d reshape
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.reshape(2,3,2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [7]:
#multi to 1d
a=np.array([[1,2,3],[4,5,6]])
print(a.reshape(-1))
b=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
b.reshape(-1)





[1 2 3 4 5 6]


array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13])

In [29]:
#slicing
a=np.array([1,2,3,4,5])
print(a[1:3])
print(a[:5])
print(a[-3:-1])
print(a[1:4:2])
print(a[::2])


[2 3]
[1 2 3 4 5]
[3 4]
[2 4]
[1 3 5]


In [35]:
#slicing in 2d
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,1:4])
a=np.array([[2,5,8,9],[6,3,7,4],[6,7,3,3]])
print(a[2,1:3])
print(a[0:3,1:3])


[2 3 4]
[7 3]
[[5 8]
 [3 7]
 [7 3]]


In [52]:
#casting
a=np.array([1,2,3,0],dtype=bool)
print(a)
print(a.dtype)


[ True  True  True False]
bool


In [54]:
a=np.array([1,2,3,4])#casting
a=a.astype('complex128')
print(a)
print(a.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [55]:
#sorting in 1d
a=np.array([2,5,1,6,9])
print(np.sort(a))

[1 2 5 6 9]


In [64]:
#sorting in 2d
a=np.array([[3,5,1,6],[7,3,5,1]])
print(np.sort(a))
np.where(a==5)#where function is used to tell the index position in array



[[1 3 5 6]
 [1 3 5 7]]


(array([0, 1], dtype=int64), array([1, 2], dtype=int64))

In [9]:
#swapping
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:,::-1])#reversing elements in array
print(a[::-1,::-1])#swapping


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# a=np.array([1,6,2,8,3,9])
k=np.searchsorted(a,9,side='right')#doubt
x=np.searchsorted(a,6,side='right')
print(k)
print(x)

In [88]:
#multiply
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
print(a*b)
print(np.multiply(a,b))

[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]
